# Use an official Node runtime as a parent image
FROM node:21-bullseye

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and yarn.lock or package-lock.json files to the container
COPY package*.json ./

# Install app dependencies
RUN yarn install --production

RUN yarn cache clean

# Copy the rest of the application files to the container
COPY . .

# Build
RUN yarn build

# Define the command to run the application in production mode
CMD ["yarn", "run", "start"]


