export const ROUTE_PATHS = {
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT: "/product/:product",
  ABOUT: "/about",
  MY_ACCOUNT: "/my-account",
  ADMIN: "/admin/manage-products",
  ADMIN_EDIT_PRODUCT: "/admin/manage-products/edit/:id",
  ADMIN_CREATE_PRODUCT: "/admin/manage-products/create-product",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  PRIVACY_POLICY: "/privacy-policy",
  BUY_SUCCESS: "/success",
  RECOVER_PASSWORD: "/recover-password",
  POLICIES: "/terms-of-service",
  SHIPPING_POLICIES: "/shipping-policies",
  REFUND_POLICIE: "/refund-policies",
  BLOG_: "/blog",
  TESTEMONIALS: "/testemonials",
  CONTACTS: "/contacts",
};
